site_name: Discord User Documentation

docs_dir: docs

theme:
  name: material
  features:
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: setup.md
  - Server Setup: server.md
  - Channel Management: channel.md
  - Meetings: meeting.md
  - Troubleshooting: Troubleshooting.md
  - Glossary: Glossary.md
